apiVersion: v1
kind: PersistentVolume
metadata:
  name: chatglm2-6b
spec:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  csi:
    driver: tos.csi.volcengine.com
    nodePublishSecretRef:
      name: tos-secret
      namespace: default
    volumeAttributes:
      bucket: chatglm2
      path: /data
      url: http://tos-s3-cn-beijing.ivolces.com
    volumeHandle: chatglm2-6b
  persistentVolumeReclaimPolicy: Retain
  volumeMode: Filesystem
