apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: chatglm2-6b
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  volumeMode: Filesystem
  volumeName: chatglm2-6b
