name: Deploy to Kubernetes

on:
  workflow_dispatch:
  
  pull_request:
    branches: [ main ]
    paths:
      - 'deploy/k8s'
      - '.github/workflows/deploy_k8s.yml'

jobs:
  deploy:
    name: Deploy to Kubernetes
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Create kubeconfig
      run: |
        mkdir ${HOME}/.kube
        echo ${{ secrets.KUBE_CONFIG_BJ_STAR_POC }} > ${HOME}/.kube/config
    - name: Use context
      run: kubectl config use-context cck05qihqh4vnis1kvch0@1007107-kck0hibj3830ifk6eqgtg
    - name: Deploy to K8s
      run: kubectl apply -f deploy/k8s
